---
# tasks file for sap
- name: Deploy custom facts
  ansible.builtin.import_tasks: facts.yml

- name: Deploy SAP folder structure
  ansible.builtin.import_tasks: folder.yml

- name: Deploy custom SAP firewall configuration
  ansible.builtin.import_tasks: firewall.yml

- name: Deploy SAP management scripts
  ansible.builtin.import_tasks: scripts.yml

- name: Activate base RHEL SAP subscriptions
  ansible.builtin.import_tasks: subscription.yml
  when:
    - (ansible_facts['virtualization_type'] != "container") and
      (ansible_facts['virtualization_type'] != "docker")
    - ansible_facts['distribution'] == "RedHat"
    - rhn_manage|bool
    - rhn_organization_id != "unset"
    - rhn_activation_key != "unset"
    - rhn_pool_id != "unset"

- name: Add SAP repositories
  ansible.builtin.import_tasks: repositories.yml
  when:
    - rhn_manage|bool
    - ansible_facts['distribution'] == "RedHat"
    - (ansible_facts['virtualization_type'] != "container") and
      (ansible_facts['virtualization_type'] != "docker")

- name: Deploy SAP packages
  ansible.builtin.import_tasks: packages.yml

- name: Deploy uuidd
  ansible.builtin.import_tasks: uuidd.yml

- name: Deploy ODBC
  ansible.builtin.import_tasks: odbc.yml

- name: Configure SAP profile
  ansible.builtin.import_tasks: profile.yml
  when:
    - ansible_facts['distribution'] == "RedHat"

- name: Deploy SAP configuration
  ansible.builtin.import_tasks: sapconf.yml
  when:
    - ansible_facts['distribution'] == "RedHat"

- name: Configure tmpfile support
  ansible.builtin.import_tasks: tmpfile.yml

- name: Configure tmpfs size
  ansible.builtin.import_tasks: tmpfs.yml

- name: Deploy customized message of the day
  ansible.builtin.import_tasks: motd.yml
  when:
    - sap_motd|bool

- name: Deploy Pacemaker high-availability
  ansible.builtin.import_tasks: pacemaker.yml
  when:
    - sap_ha|bool

- name: Deploy SAP router
  ansible.builtin.import_tasks: router.yml
  when:
    - sap_custom|bool
    - sap_router|bool
