---
- name: Enable RHEL 8 SAP repositories
  community.general.rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop: "{{ rhel_repos_8_sap }}"
  when:
    - rhel_repos_8_sap is defined
    - (rhn_activation_key == "Standard-SAP-RHEL") or
      (rhn_activation_key == "Premium-SAP-RHEL") or
      (rhn_activation_key == "Developer-RHEL")
    - ansible_facts['distribution_major_version']|int == 8

- name: Enable RHEL 8 SAP E4S repositories
  community.general.rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop: "{{ rhel_repos_8_sap_e4s }}"
  when:
    - rhel_repos_8_sap_e4s is defined
    - rhn_repo_e4s|bool
    - (rhn_activation_key == "Standard-SAP-RHEL") or
      (rhn_activation_key == "Premium-SAP-RHEL") or
      (rhn_activation_key == "Developer-RHEL")
    - ansible_facts['distribution_major_version']|int == 8

- name: Enable RHEL 8 SAP EUS repositories
  community.general.rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop: "{{ rhel_repos_8_sap_eus }}"
  when:
    - rhel_repos_8_sap_eus is defined
    - rhn_repo_eus|bool
    - (rhn_activation_key == "Standard-SAP-RHEL") or
      (rhn_activation_key == "Premium-SAP-RHEL") or
      (rhn_activation_key == "Developer-RHEL")
    - ansible_facts['distribution_major_version']|int == 8

- name: Enable RHEL 9 SAP repositories
  community.general.rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop: "{{ rhel_repos_9_sap }}"
  when:
    - rhel_repos_9_sap is defined
    - (rhn_activation_key == "Standard-SAP-RHEL") or
      (rhn_activation_key == "Premium-SAP-RHEL") or
      (rhn_activation_key == "Developer-RHEL")
    - ansible_facts['distribution_major_version']|int == 9
