---
- name: Register in RHN with RHEL development subscription
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ rhn_activation_key }}"
    org_id: "{{ rhn_organization_id }}"
    pool: "{{ rhn_pool_id }}"
    syspurpose:
      usage: "Development/Test"
      role: "Red Hat Enterprise Linux Server"
      service_level_agreement: "Self-Support"
      sync: true
  when:
    - ansible_facts['distribution'] == "RedHat"
    - rhn_activation_key == "Developer-RHEL"
    - (rhn_organization_id != "unset") or
      (rhn_pool_id != "unset")

- name: Register in RHN with RHEL standard subscription
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ rhn_activation_key }}"
    org_id: "{{ rhn_organization_id }}"
    pool: "{{ rhn_pool_id }}"
    syspurpose:
      usage: "Production"
      role: "Red Hat Enterprise Linux Server"
      service_level_agreement: "Standard"
      sync: true
  when:
    - ansible_facts['distribution'] == "RedHat"
    - rhn_activation_key == "Standard-RHEL"
    - (rhn_organization_id != "unset") or
      (rhn_pool_id != "unset")

- name: Register in RHN with RHEL SAP standard subscription
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ rhn_activation_key }}"
    org_id: "{{ rhn_organization_id }}"
    pool: "{{ rhn_pool_id }}"
    syspurpose:
      usage: "Production"
      role: "Not Specified"
      service_level_agreement: "Standard"
      sync: true
  when:
    - ansible_facts['distribution'] == "RedHat"
    - rhn_activation_key == "Standard-SAP-RHEL"
    - (rhn_organization_id != "unset") or
      (rhn_pool_id != "unset")

- name: Register in RHN with RHEL SAP premium subscription
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ rhn_activation_key }}"
    org_id: "{{ rhn_organization_id }}"
    pool: "{{ rhn_pool_id }}"
    syspurpose:
      usage: "Production"
      role: "Red Hat Enterprise Linux Server"
      service_level_agreement: "Premium"
      sync: true
  when:
    - ansible_facts['distribution'] == "RedHat"
    - rhn_activation_key == "Premium-SAP-RHEL"
    - (rhn_organization_id != "unset") or
      (rhn_pool_id != "unset")
