---
# handlers file for sap
- name: Reload firewalld
  ansible.builtin.command:
    cmd: firewall-cmd --reload
  register: firewall_reload
  changed_when: firewall_reload.rc != 0
  when:
    - (ansible_facts['virtualization_type'] != "container") and
      (ansible_facts['virtualization_type'] != "docker")

- name: Restart SAP Router
  ansible.builtin.service:
    name: sap-router.service
    state: restarted
